<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zend\\' => array($vendorDir . '/zendframework/zendframework/library'),
    'ZendTest\\' => array($vendorDir . '/zendframework/zendframework/tests'),
    'ZendOAuth' => array($vendorDir . '/zendframework/zendoauth/library'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Elastica\\Test' => array($vendorDir . '/ruflin/elastica/test/lib'),
    'Elastica' => array($vendorDir . '/ruflin/elastica/lib'),
    'Compilation' => array($baseDir . '/'),
    'Change' => array($baseDir . '/'),
);
