<?php
namespace ChangeTests\Change\I18n;

use Change\I18n\I18nManager;


class I18nManagerTest extends \ChangeTests\Change\TestAssets\TestCase
{
	protected function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		// Stop logging non existent keys.
		$callback = function (\Change\Events\Event $event)
		{
			// Add '--' before key to validate that this callback is really used.
			return '--' . $event->getParam('preparedKey')->getKey();
		};
		$this->getApplicationServices()->getI18nManager()->getEventManager()->attach(I18nManager::EVENT_KEY_NOT_FOUND, $callback, 10);

		$callback = function (\Zend\EventManager\Event $event)
		{
			$formatters = $event->getParam('formatters');
			if (in_array('required', $formatters))
			{
				if (in_array('html', $formatters))
				{
					$event->setParam('text', '<span class="required">*</span> ' . $event->getParam('text'));
				}
				else
				{
					$event->setParam('text', '* ' . $event->getParam('text'));
				}
			}
		};
		$this->getApplicationServices()->getI18nManager()->getEventManager()->attach(I18nManager::EVENT_FORMATTING, $callback, 2);
	}

	public function testIsValidLCID()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertTrue($manager->isValidLCID('fr_FR'));
		$this->assertTrue($manager->isValidLCID('en_GB'));
		$this->assertTrue($manager->isValidLCID('to_TO'));
		$this->assertTrue($manager->isValidLCID('ab_CD'));
		$this->assertFalse($manager->isValidLCID('toto'));
		$this->assertFalse($manager->isValidLCID('FR_FR'));
		$this->assertFalse($manager->isValidLCID('fr_fr'));
		$this->assertFalse($manager->isValidLCID('FR_fr'));
		$this->assertFalse($manager->isValidLCID('a8_A9'));
		$this->assertFalse($manager->isValidLCID('fr-FR'));
		$this->assertFalse($manager->isValidLCID('fr_FR '));
		$this->assertFalse($manager->isValidLCID(' fr_FR'));
		$this->assertFalse($manager->isValidLCID('fr__FR'));
	}

	public function testGetSupportedLCIDs()
	{
		$application = $this->getApplication();
		$config = $application->getConfiguration();
		$config->addVolatileEntry('Change/I18n/supported-lcids', null);
		$config->addVolatileEntry('Change/I18n/supported-lcids', array('fr_FR', 'en_US', 'it_IT', 'es_ES', 'en_GB'));

		$config->addVolatileEntry('Change/I18n/langs', null);
		$config->addVolatileEntry('Change/I18n/langs', array('en_US' => 'us'));

		$manager = new I18nManager();
		$manager->setApplication($application);

		$this->assertEquals(array('fr_FR', 'en_US', 'it_IT', 'es_ES', 'en_GB'), $manager->getSupportedLCIDs());
		return $manager;
	}

	/**
	 */
	public function testSupportsMultipleLCIDs()
	{
		$application = $this->getApplication();
		$config = $application->getConfiguration();

		$config->addVolatileEntry('Change/I18n/supported-lcids', null);
		$manager = new I18nManager();
		$manager->setApplication($application);
		$this->assertFalse($manager->supportsMultipleLCIDs());

		$config->addVolatileEntry('Change/I18n/supported-lcids', array('fr_FR'));
		$manager = new I18nManager();
		$manager->setApplication($application);
		$this->assertFalse($manager->supportsMultipleLCIDs());

		$config->addVolatileEntry('Change/I18n/supported-lcids', array('fr_FR', 'en_US'));
		$manager = new I18nManager();
		$manager->setApplication($application);
		$this->assertTrue($manager->supportsMultipleLCIDs());

		$config->addVolatileEntry('Change/I18n/supported-lcids', array('fr_FR', 'en_US', 'it_IT', 'es_ES', 'en_GB'));
		$manager = new I18nManager();
		$manager->setApplication($application);
		$this->assertTrue($manager->supportsMultipleLCIDs());
	}

	/**
	 */
	public function testHasGetI18nSynchro()
	{
		$application = $this->getApplication();
		$config = $application->getConfiguration();
		$config->addVolatileEntry('Change/I18n/supported-lcids', array('fr_FR', 'en_US', 'it_IT', 'es_ES', 'en_GB'));
		$configArray = $config->getConfigArray();

		$config->addVolatileEntry('Change/I18n/synchro/keys', array());
		$manager = new I18nManager();
		$manager->setApplication($application);
		$this->assertFalse($manager->hasI18nSynchro());
		$this->assertEquals(array(), $manager->getI18nSynchro());

		$config->setConfigArray($configArray);
		$config->addVolatileEntry('Change/I18n/synchro/keys', array('en_US' => array('fr_FR')));
		$manager = new I18nManager();
		$manager->setApplication($application);
		$this->assertTrue($manager->hasI18nSynchro());
		$this->assertEquals(array('en_US' => array('fr_FR')), $manager->getI18nSynchro());

		$config->setConfigArray($configArray);
		$config->addVolatileEntry('Change/I18n/synchro/keys',
			array('en_US' => array('fr_FR'), 'en_GB' => array('en_US', 'fr_FR')));
		$manager = new I18nManager();
		$manager->setApplication($application);
		$this->assertTrue($manager->hasI18nSynchro());
		$this->assertEquals(array('en_US' => array('fr_FR'), 'en_GB' => array('en_US', 'fr_FR')), $manager->getI18nSynchro());

		// Unsupported LCIDs are ignored
		$config->setConfigArray($configArray);
		$config->addVolatileEntry('Change/I18n/synchro/keys',
			array('en_US' => array('fr_FR', 'kl_KL'), 'to_TO' => array('fr_FR')));
		$manager = new I18nManager();
		$manager->setApplication($application);
		$this->assertTrue($manager->hasI18nSynchro());
		$this->assertEquals(array('en_US' => array('fr_FR')), $manager->getI18nSynchro());
	}

	/**
	 * @depends testGetSupportedLCIDs
	 */
	public function testGetDefaultLang(I18nManager $manager)
	{
		$this->assertEquals('fr_FR', $manager->getDefaultLCID());
	}

	/**
	 * @depends testGetSupportedLCIDs
	 */
	public function testGetLangByLCID(I18nManager $manager)
	{
		$this->assertEquals('fr', $manager->getLangByLCID('fr_FR'));
		$this->assertEquals('us', $manager->getLangByLCID('en_US'));
		$this->assertEquals('xx', $manager->getLangByLCID('xx_XX'));
		try
		{
			$manager->getLangByLCID('fr');
			$this->fail('A InvalidArgumentException should be thrown.');
		}
		catch (\InvalidArgumentException $e)
		{
			$this->assertEquals('Not supported LCID: fr', $e->getMessage());
		}
	}

	/**
	 * @depends testGetSupportedLCIDs
	 */
	public function testGetSetLCID(I18nManager $manager)
	{
		// If no UI lang is set, use the default one.
		$this->assertEquals($manager->getDefaultLCID(), $manager->getLCID());

		// Set/get supported languages.
		$manager->setLCID('it_IT');
		$this->assertEquals('it_IT', $manager->getLCID());
		$manager->setLCID('en_US');
		$this->assertEquals('en_US', $manager->getLCID());

		// Setting an unsupported language.
		try
		{
			$manager->setLCID('kl_KL');
			$this->fail('A InvalidArgumentException should be thrown.');
		}
		catch (\InvalidArgumentException $e)
		{
			$this->assertEquals('Not supported LCID: kl_KL', $e->getMessage());
		}
	}

	public function testPrepareKeyFromTransString()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$preparedKey = $manager->prepareKeyFromTransString('m.website.fo.test,ucf,toto=titi,attr');
		$this->assertEquals('m.website.fo.test', $preparedKey->getKey());
		$this->assertEquals(array('ucf', 'attr'), $preparedKey->getFormatters());
		$this->assertEquals(array('toto' => 'titi'), $preparedKey->getReplacements());

		// Keys and formatters are lower cased and spaces are cleaned.
		$preparedKey = $manager->prepareKeyFromTransString(' m.Website.Fo.test.TEst ,uCf , toTo= titI , aTTr');
		$this->assertEquals('m.website.fo.test.test', $preparedKey->getKey());
		$this->assertEquals(array('ucf', 'attr'), $preparedKey->getFormatters());
		$this->assertEquals(array('toTo' => 'titI'), $preparedKey->getReplacements());
	}


	public function testTranslateNoKey()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$a = "çé Té tutu";
		$this->assertEquals($a, $manager->trans($a));
	}


	public function testTransForLCID()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		// Key translation.
		$this->assertEquals('plop fr a.aa', $manager->transForLCID('fr_FR', 'm.project.tests.a.plop'));
		$this->assertEquals('plip fr b', $manager->transForLCID('fr_FR', 'm.project.tests.a.plip'));
		$this->assertEquals('', $manager->transForLCID('fr_FR', 'm.project.tests.a.empty'));

		$this->assertEquals('--m.project.tests.a.plep', $manager->transForLCID('fr_FR', 'm.project.tests.a.plep'));

		$this->assertEquals('plop us a.aa', $manager->transForLCID('en_US', 'm.project.tests.a.plop'));
		// Default fallback test
		$this->assertEquals('plip fr b', $manager->transForLCID('en_US', 'm.project.tests.a.plip'));
		$this->assertEquals('--m.project.tests.a.undefinedkey', $manager->transForLCID('en_US', 'm.project.tests.a.undefinedkey'));

		$this->assertEquals('un texte quelconque', $manager->transForLCID('fr_FR', 'un texte quelconque'));

		// Converters.
		$this->assertEquals('Plop fr a.aa', $manager->transForLCID('fr_FR', 'm.project.tests.a.plop', array('ucf')));
		$this->assertEquals('un texte quelconque', $manager->transForLCID('fr_FR', 'un texte quelconque', array('ucf')));
		$this->assertEquals('PLOP FR A.AA :', $manager->transForLCID('fr_FR', 'm.project.tests.a.plop', array('uc', 'lab')));
		$this->assertEquals('un texte quelconque', $manager->transForLCID('fr_FR', 'un texte quelconque', array('uc', 'lab')));

		// Substitutions.
		$this->assertEquals('Withparams test $PARAM2$ fr a',
			$manager->transForLCID('fr_FR', 'm.project.tests.a.withparams', array('ucf'), array('PARAM1' => 'test')));
		$this->assertEquals('withparams test youpi fr a', $manager->transForLCID('fr_FR', 'm.project.tests.a.withparams', array(),
			array('PARAM1' => 'test', 'PARAM2' => 'youpi')));

		$this->assertEquals('withparams test youpi fr a', $manager->transForLCID('fr_FR', 'm.project.tests.a.withparams', array(),
			array('PaRaM1' => 'test', 'param2' => 'youpi')));

		// Key synchro.
		$config = $this->getApplication()->getConfiguration();
		$this->assertFalse($manager->hasI18nSynchro());
		$this->assertEquals('plop us a.aa', $manager->transForLCID('en_US', 'm.project.tests.a.plop'));
		$this->assertEquals('--m.project.tests.a.plop', $manager->transForLCID('en_GB', 'm.project.tests.a.plop'));

		$config->addVolatileEntry('Change/I18n/supported-lcids', array('en_GB'));
		$config->addVolatileEntry('Change/I18n/synchro/keys', array('en_GB' => array('en_US')));

		$syncManager = new I18nManager();
		$syncManager->setApplication($this->getApplication());
		$this->assertTrue($syncManager->hasI18nSynchro());
		$this->assertEquals('plop us a.aa', $syncManager->transForLCID('en_GB', 'm.project.tests.a.plop'));
		$this->assertEquals('plop us a.aa', $syncManager->transForLCID('en_US', 'm.project.tests.a.plop'));
	}


	public function testFormatText()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		// Converters.
		$this->assertEquals('Un texte quelconque', $manager->formatText('fr_FR', 'un texte quelconque', array('ucf')));
		$this->assertEquals('UN TEXTE QUELCONQUE :',
			$manager->formatText('fr_FR', 'un texte quelconque', array('uc', 'lab')));
		$this->assertEquals('UN TEXTE QUELCONQUE:',
			$manager->formatText('en_US', 'un texte quelconque', array('uc', 'lab')));

		// Substitutions.
		$this->assertEquals('Un texte pramétré test $param2$',
			$manager->formatText('fr_FR', 'un texte pramétré $param1$ $param2$', array('ucf'), array('param1' => 'test')));
		$this->assertEquals('un texte pramétré test youpi',
			$manager->formatText('fr_FR', 'un texte pramétré $param1$ $param2$', array(),
				array('param1' => 'test', 'param2' => 'youpi')));

		// Specific formatter.
		$this->assertEquals('* Un texte quelconque',
			$manager->formatText('fr_FR', 'un texte quelconque', array('required', 'ucf')));
		$this->assertEquals('<span class="required">*</span> Un texte quelconque',
			$manager->formatText('fr_FR', 'un texte quelconque', array('ucf', 'required', 'html')));
	}

	/**
	 * @depends testTransForLCID
	 */
	public function testTrans()
	{
		$manager = $this->getApplicationServices()->getI18nManager();

		$this->assertEquals('fr_FR', $manager->getLCID());

		// Key translation.
		$this->assertEquals('plop fr a.aa', $manager->trans('m.project.tests.a.plop'));
		$this->assertEquals('plip fr b', $manager->trans('m.project.tests.a.plip'));
		$this->assertEquals('--m.project.tests.a.plep', $manager->trans('m.project.tests.a.plep'));
		$this->assertEquals('un texte quelconque', $manager->trans('un texte quelconque'));

		// Converters.
		$this->assertEquals('Plop fr a.aa', $manager->trans('m.project.tests.a.plop', array('ucf')));
		$this->assertEquals('un texte quelconque', $manager->trans('un texte quelconque', array('ucf')));
		$this->assertEquals('PLOP FR A.AA :', $manager->trans('m.project.tests.a.plop', array('uc', 'lab')));
		$this->assertEquals('un texte quelconque', $manager->trans('un texte quelconque', array('uc', 'lab')));

		// Substitutions.
		$this->assertEquals('Withparams test $PARAM2$ fr a',
			$manager->trans('m.project.tests.a.withparams', array('ucf'), array('param1' => 'test')));
		$this->assertEquals('withparams test youpi fr a',
			$manager->trans('m.project.tests.a.withparams', array(), array('param1' => 'test', 'param2' => 'youpi')));
	}

	// Dates.

	/**
	 * Tests for:
	 *  - get/setDateFormat
	 *  - get/setDateTimeFormat
	 *  - get/setTimeZone
	 */
	public function testGetSetDateFormatsAndTimeZone()
	{
		$manager = $this->getApplicationServices()->getI18nManager();

		// If no values set, use the default ones.
		$config = $this->getApplication()->getConfiguration();
		$this->assertEquals($config->getEntry('Change/I18n/default-timezone'), $manager->getTimeZone()->getName());
		foreach (array('fr_FR', 'en_US') as $lang)
		{
			$this->assertEquals($manager->transForLCID($lang, 'c.date.default_date_format'), $manager->getDateFormat($lang));
			$this->assertEquals($manager->transForLCID($lang, 'c.date.default_datetime_format'),
				$manager->getDateTimeFormat($lang));
		}

		// If values are set, these values are returned.
		$manager->setDateFormat('test');
		$this->assertEquals('test', $manager->getDateFormat('fr_FR'));
		$this->assertEquals('test', $manager->getDateFormat('en_US'));

		$manager->setDateTimeFormat('toto');
		$this->assertEquals('toto', $manager->getDateTimeFormat('fr_FR'));
		$this->assertEquals('toto', $manager->getDateTimeFormat('en_US'));

		$manager->setTimeZone('Asia/Tokyo'); // Time zone may be set by code...
		$this->assertEquals('Asia/Tokyo', $manager->getTimeZone()->getName());
		$manager->setTimeZone(new \DateTimeZone('America/New_York')); // ... or by DateTimeZone instance.
		$this->assertEquals('America/New_York', $manager->getTimeZone()->getName());

		// Admitted values for following tests.
		$manager->setTimeZone('Europe/Paris');
		$this->assertEquals('Europe/Paris', $manager->getTimeZone()->getName());
		$manager->setDateFormat('dd/MM/yyyy');
		$this->assertEquals('dd/MM/yyyy', $manager->getDateFormat($manager->getLCID()));
		$manager->setDateTimeFormat('dd/MM/yyyy HH:mm');
		$this->assertEquals('dd/MM/yyyy HH:mm', $manager->getDateTimeFormat($manager->getLCID()));
	}

	/**
	 * @depends testGetSetDateFormatsAndTimeZone
	 */
	public function testGetLocalDateTime()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$date = $manager->getLocalDateTime('2012-10-16 09:00:00');
		$this->assertEquals('Europe/Paris', $date->getTimezone()->getName());
		$this->assertEquals('2012-10-16 09:00:00', $date->format('Y-m-d H:i:s'));
		return $date;
	}

	/**
	 * @depends testGetSetDateFormatsAndTimeZone
	 */
	public function testGetGMTDateTime()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$date = $manager->getGMTDateTime('2012-10-16 09:00:00');
		$this->assertEquals('UTC', $date->getTimezone()->getName());
		$this->assertEquals('2012-10-16 09:00:00', $date->format('Y-m-d H:i:s'));
	}

	/**
	 * @depends testGetSetDateFormatsAndTimeZone
	 */
	public function testToGMTDateTime()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$date = $manager->getLocalDateTime('2012-10-16 09:00:00');
		$manager->toGMTDateTime($date);
		$this->assertEquals('UTC', $date->getTimezone()->getName());
		$this->assertEquals('2012-10-16 07:00:00', $date->format('Y-m-d H:i:s'));
	}

	/**
	 * @depends testGetSetDateFormatsAndTimeZone
	 */
	public function testToLocalDateTime()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$date = $manager->getGMTDateTime('2012-10-16 09:00:00');
		$manager->toLocalDateTime($date);
		$this->assertEquals('Europe/Paris', $date->getTimezone()->getName());
		$this->assertEquals('2012-10-16 11:00:00', $date->format('Y-m-d H:i:s'));
	}

	/**
	 * @depends testGetSetDateFormatsAndTimeZone
	 */
	public function testFormatDate()
	{
		$manager = $this->getApplicationServices()->getI18nManager();

		// Basic formatting.
		$date = $manager->getLocalDateTime('2012-10-16 09:00:00');
		$this->assertEquals('16/10/2012 09:00', $manager->formatDate('fr_FR', $date, 'dd/MM/yyyy HH:mm'));

		// The language is correctly used for days and months.
		$this->assertEquals('mardi, 16 octobre 2012', $manager->formatDate('fr_FR', $date, 'EEEE, d MMMM yyyy'));
		$this->assertEquals('Tuesday, October 16 2012', $manager->formatDate('en_US', $date, 'EEEE, MMMM d yyyy'));

		// Without any specified time zone, the date is converted to the local timezone.
		$this->assertEquals('09:00 UTC+02:00', $manager->formatDate('fr_FR', $date, 'HH:mm ZZZZ'));
		$gmtDate = $manager->getGMTDateTime('2012-10-16 09:00:00');
		$this->assertEquals('11:00 UTC+02:00', $manager->formatDate('fr_FR', $gmtDate, 'HH:mm ZZZZ'));

		// If there is a specified time zone, the date is converted to it.
		$dt = $manager->formatDate('fr_FR', $date, 'HH:mm ZZZZ', new \DateTimeZone('America/New_York'));
		if (strpos($dt, '-'))
		{
			$this->assertEquals('03:00 UTC-04:00', $dt);
		}
		else
		{
			//TODO fix this php 5.4.15 bug
			$this->assertEquals('03:00 UTC−04:00', $dt);
		}


		$this->assertEquals('18:00 UTC+09:00',
			$manager->formatDate('fr_FR', $gmtDate, 'HH:mm ZZZZ', new \DateTimeZone('Asia/Tokyo')));
	}

	/**
	 * @depends testGetSetDateFormatsAndTimeZone
	 */
	public function testTransDate()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$date = $manager->getLocalDateTime('2012-10-16 09:00:00');
		$this->assertEquals('dd/MM/yyyy', $manager->getDateFormat($manager->getLCID()));
		$this->assertEquals('16/10/2012', $manager->transDate($date));
	}

	/**
	 * @depends testGetSetDateFormatsAndTimeZone
	 */
	public function testTransDateTime()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$date = $manager->getLocalDateTime('2012-10-16 09:00:00');
		$this->assertEquals('dd/MM/yyyy HH:mm', $manager->getDateTimeFormat($manager->getLCID()));
		$this->assertEquals('16/10/2012 09:00', $manager->transDateTime($date));
	}

	// Transformers.


	public function testTransformLab()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals('test :', $manager->transformLab('test', 'fr_FR'));
		$this->assertEquals('test:', $manager->transformLab('test', 'en_US'));
	}

	public function testTransformUc()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals('TEST', $manager->transformUc('test', 'fr_FR'));
		$this->assertEquals('TEST', $manager->transformUc('tEsT', 'fr_FR'));
		$this->assertEquals('ÉTÉ ÇA', $manager->transformUc('été ça', 'fr_FR'));
	}

	public function testTransformUcf()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals('Test', $manager->transformUcf('test', 'fr_FR'));
		$this->assertEquals('TEsT', $manager->transformUcf('tEsT', 'fr_FR'));
		$this->assertEquals('Été ça', $manager->transformUcf('été ça', 'fr_FR'));
	}

	public function testTransformUcw()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals('Test Test', $manager->transformUcw('test test', 'fr_FR'));
		$this->assertEquals('Test', $manager->transformUcw('tEsT', 'fr_FR'));
		$this->assertEquals('Été Ça', $manager->transformUcw('été ça', 'fr_FR'));
	}

	public function testTransformLc()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals('test test', $manager->transformLc('test test', 'fr_FR'));
		$this->assertEquals('test', $manager->transformLc('tEsT', 'fr_FR'));
		$this->assertEquals('été ça été', $manager->transformLc('été ça Été', 'fr_FR'));
	}


	public function testTransformJs()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals('test \"test\"', $manager->transformJs('test "test"', 'fr_FR'));
		$this->assertEquals('tEsT \t \n \\\'test\\\' \\\\', $manager->transformJs("tEsT \t \n 'test' \\", 'fr_FR'));
	}

	public function testTransformHtml()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals("test <br />\n &lt;em&gt;toto&lt;/em&gt; &quot;test&quot;",
			$manager->transformHtml("test \n <em>toto</em> \"test\"", 'fr_FR'));
	}

	public function testTransformText()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$source = '<h1>Titre</h1><p>Un<br/>paragraphe</p><ul><li>item 1</li><li>item 2</li></ul><hr><div class="test">Contenu du div</div>';
		$expected =
			'Titre' . PHP_EOL . 'Un' . PHP_EOL . 'paragraphe' . PHP_EOL . ' * item 1' . PHP_EOL . ' * item 2' . PHP_EOL . '------'
			. PHP_EOL . 'Contenu du div';
		$this->assertEquals($expected, $manager->transformText($source, 'fr_FR'));

		$source = '<table><tr><th>Titre 1</th><th>Titre 2</th></tr><tr><td>Cellule 1</td><td>Cellule 2</td></tr><table>';
		$expected = "Titre 1\tTitre 2\t" . PHP_EOL . "Cellule 1\tCellule 2";
		$this->assertEquals($expected, $manager->transformText($source, 'fr_FR'));
	}


	public function testTransformAttr()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals("test&quot;sqdqs&quot; qsdqsd&lt;sdsdf&gt;",
			$manager->transformAttr('test"sqdqs" qsdqsd<sdsdf>', 'fr_FR'));
	}

	public function testTransformSpace()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals(" test 3 ", $manager->transformSpace("test 3", 'fr_FR'));
		$this->assertEquals(" ... ", $manager->transformSpace("...", 'fr_FR'));
	}

	public function testTransformEtc()
	{
		$manager = $this->getApplicationServices()->getI18nManager();
		$this->assertEquals("test 3...", $manager->transformEtc("test 3", 'fr_FR'));
		$this->assertEquals("......", $manager->transformEtc("...", 'fr_FR'));
	}
}